#!/usr/bin/env python3
"""Validate commit subjects against the convention, locally and in CI from one implementation.

**A squash merge with a single commit takes the subject from the commit, not from the pull request
title.** That is documented in .github/workflows/pr-title-check.yml, which grew a second job for it
after a `verify:` subject reached main on 2026-09-11.

This exists because of the adjacent failure. On 2026-09-13 a 76-character subject reached main while
the check that catches it was red: the check ran only in CI, the merge happened before its result was
read, and nothing on the machine that wrote the commit could have said so. **A gate that only runs
after the push is a gate whose result competes with the merge.**

So the same validation runs in `make all`. It is not a second implementation -- the workflow calls
this script, so there is one pattern and one length limit rather than two that can drift.

The range is `origin/main..HEAD` by default, which is empty on main itself and passes. It cannot
check a commit that does not exist yet, so the order that catches everything is: commit, run the
gate, push. CONTRIBUTING states that order.

Run:  python3 tools/check_commit_subjects.py [--base <ref>] [--author <login>]
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys

# The types and the two limits are here and nowhere else. The workflow imports the behaviour by
# calling this file; AGENTS.md and CONTRIBUTING.md describe it in prose, and prose that disagrees
# with this is wrong by construction.
PATTERN = re.compile(
    r"^(feat|fix|docs|chore|refactor|test|ci|perf|style|bench)(\([a-z0-9-]+\))?: .+"
)
SUBJECT_MAX = 72
# A pull request title is capped tighter than a commit subject, and always has been. The two limits
# live here together so that the reason they differ is visible rather than split across two jobs.
TITLE_MAX = 70

# Keyed on the author rather than on the subject, for the reason the workflow gives: allowing a
# subject pattern would let a human write one and skip the rule; allowing an account cannot.
BOTS = frozenset(
    {
        "renovate[bot]",
        "dependabot[bot]",
        "github-actions[bot]",
        "pre-commit-ci[bot]",
    }
)


def commits(base: str, head: str) -> list[tuple[str, str]]:
    """Non-merge commits in the range, as (short sha, subject).

    Merge commits are excluded: their subjects are generated by the platform, and a branch updated
    from main carries one through no fault of the author.

    Split on the first space: an abbreviated SHA cannot contain one, so everything after it is the
    subject however many spaces or colons it holds.
    """
    result = subprocess.run(
        ["git", "log", "--no-merges", "--format=%h %s", f"{base}..{head}"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        # An unknown base is not a pass. A fresh clone without origin/main, or a typo in --base,
        # would otherwise report a clean run over an empty range.
        raise SystemExit(
            f"commit-subjects: cannot read {base}..{head}: {result.stderr.strip()}\n"
            "  A range that cannot be read is not an empty range. Fetch the base ref, or pass "
            "--base explicitly."
        )
    out: list[tuple[str, str]] = []
    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        sha, _, subject = line.partition(" ")
        out.append((sha, subject))
    return out


def check(pairs: list[tuple[str, str]], maximum: int = SUBJECT_MAX) -> list[str]:
    problems: list[str] = []
    for sha, subject in pairs:
        if not PATTERN.match(subject):
            problems.append(
                f"{sha}: subject must follow conventional commits\n"
                f"    got:      {subject}\n"
                "    expected: <type>(<optional-scope>): <description>"
            )
            continue
        if len(subject) > maximum:
            problems.append(
                f"{sha}: subject is {len(subject)} characters; keep it under {maximum}\n"
                f"    got: {subject}"
            )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default="origin/main")
    parser.add_argument("--head", default="HEAD")
    parser.add_argument("--author", default="")
    parser.add_argument(
        "--subject",
        default=None,
        help="Validate one string instead of a range -- the pull request title. Uses TITLE_MAX.",
    )
    args = parser.parse_args()

    if args.author in BOTS:
        print(
            f"commit-subjects: {args.author} is a known bot; the convention is not enforced."
        )
        return 0

    # One string rather than a range: the pull request title. That job used to carry its own copy of
    # the pattern, which is the drift this file exists to prevent -- a type accepted in a commit and
    # rejected in a title is a rule nobody can follow.
    if args.subject is not None:
        problems = check([("title", args.subject)], maximum=TITLE_MAX)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        if problems:
            return 1
        print(f"commit-subjects: title OK ({len(args.subject)} characters)")
        return 0

    pairs = commits(args.base, args.head)
    if not pairs:
        print(f"commit-subjects: no non-merge commits in {args.base}..{args.head}")
        return 0

    problems = check(pairs)
    for problem in problems:
        print(f"  {problem}", file=sys.stderr)
    if problems:
        print(
            f"commit-subjects: {len(problems)} of {len(pairs)} subject(s) rejected.\n"
            "  A squash merge with a single commit takes the subject from the commit, not from the "
            "pull request title. Amend the commit rather than renaming the pull request.",
            file=sys.stderr,
        )
        return 1

    print(f"commit-subjects: {len(pairs)} subject(s) OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
